name: Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Build and Upload Builds (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x' # Targets the latest .NET 10 SDK

      - name: Publish for Linux x64
        if: matrix.os == 'ubuntu-latest'
        run: dotnet publish -c Release -r linux-x64 -p:PublishTrimmed=true

      - name: Publish for Linux ARM64
        if: matrix.os == 'ubuntu-latest'
        run: dotnet publish -c Release -r linux-arm64 -p:PublishTrimmed=true

      - name: Publish for Windows x64
        if: matrix.os == 'windows-latest'
        shell: bash
        run: dotnet publish -c Release -r win-x64 -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe

      - name: Publish for Windows Arm64
        if: matrix.os == 'windows-latest'
        shell: bash
        run: dotnet publish -c Release -r win-arm64 -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:OutputType=WinExe

      - name: Publish for macOS x64
        if: matrix.os == 'macos-latest'
        shell: bash
        run: dotnet publish -c Release -r osx-x64 -p:PublishTrimmed=true

      - name: Publish for macOS ARM64
        if: matrix.os == 'macos-latest'
        shell: bash
        run: dotnet publish -c Release -r osx-arm64 -p:PublishTrimmed=true
        
      - name: Create macOS universal2 binary
        if: matrix.os == 'macos-latest'
        shell: bash
        working-directory: DanteLogger/bin/Release/net10.0/
        run: |
          lipo -create -output DanteLogger-macos-universal osx-x64/publish/DanteLogger osx-arm64/publish/DanteLogger
          codesign -fs - --deep DanteLogger-macos-universal

      # We need to tarball our macOS and Linux builds, since the ZIP files created by upload-artifact do not retain extended unix file permissions, 
      # which means the executable bit is lost, which is un-ideal for end users, who will hit weird errors (especially relating to code signing on macOS)
      - name: 'Tar macOS universal2 build'
        if: matrix.os == 'macos-latest'
        working-directory: DanteLogger/bin/Release/net10.0/
        run: tar -cvf DanteLogger-macOS.tar DanteLogger-macos-universal 

      - name: 'Tar Linux x64'
        if: matrix.os == 'ubuntu-latest'
        working-directory: DanteLogger/bin/Release/net10.0/linux-x64/publish/
        run: tar -cvf DanteLogger-x64.tar *

      - name: 'Tar Linux ARM64'
        if: matrix.os == 'ubuntu-latest'
        working-directory: DanteLogger/bin/Release/net10.0/linux-arm64/publish/
        run: tar -cvf DanteLogger-arm64.tar *

      - name: Upload Linux x64 build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: "DanteLogger for Linux x64"
          path: "DanteLogger/bin/Release/net10.0/linux-x64/publish/DanteLogger-x64.tar"
          if-no-files-found: error
          retention-days: 30
          
      - name: Upload Linux ARM64 build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: "DanteLogger for Linux ARM64"
          path: "DanteLogger/bin/Release/net10.0/linux-arm64/publish/DanteLogger-arm64.tar"
          if-no-files-found: error
          retention-days: 30

      - name: Upload Windows x64 build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: "DanteLogger for Windows x64"
          path: "DanteLogger/bin/Release/net10.0/win-x64/publish/DanteLogger.exe"
          if-no-files-found: error
          retention-days: 30
          
      - name: Upload Windows Arm64 build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: "DanteLogger for Windows Arm64"
          path: "DanteLogger/bin/Release/net10.0/win-arm64/publish/DanteLogger.exe"
          if-no-files-found: error
          retention-days: 30

      - name: Upload macOS universal2 build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v7
        with:
          name: "DanteLogger for macOS universal2"
          path: "DanteLogger/bin/Release/net10.0/DanteLogger-macOS.tar"
          if-no-files-found: error
          retention-days: 30